[alias]
build-riscv = "build --target riscv32imac-unknown-none-elf"
build-bin = "objcopy -- -O binary rr_micro_os.bin"
build-disasm = "objdump --bin rr_micro_os -- -d"

[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tsrc/link.x"]